version: '3'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/manasgramback
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ''
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: { }